version: '2'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  nginx:
    ports:
      - 80:80
    build: ./nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
