version: '2'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - REGION=ap-northeast-1
      - S3_BUCKET_NAME=sts
  nginx:
    ports:
      - 80:80
    build: ./nginx
    volumes:
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html/:/usr/share/nginx/html
