version: '2'
services:
  api:
    build: ./
    env_file: ./.env
  nginx:
    ports:
      - 8081:80
    build: ./docker/nginx
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
